apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: customer1-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2a28bcba-7bcb-492f-b034-87d76836051b"
    keyvaultName: "d11s-kv-mercury-staging"
    tenantId: "480dcc85-c1a6-45ad-b7f9-d4b3e55c16f4"
    objects: |
      array:
        - |
          objectName: customer1-db-user
          objectType: secret
        - |
          objectName: customer1-db-password
          objectType: secret
  secretObjects:
    - secretName: customer1-db-credentials
      type: kubernetes.io/basic-auth
      data:
        - objectName: customer1-db-user
          key: username
        - objectName: customer1-db-password
          key: password
    - secretName: customer1-n8n-env
      type: Opaque
      data:
        - objectName: customer1-db-user
          key: DB_POSTGRESDB_USER
        - objectName: customer1-db-password
          key: DB_POSTGRESDB_PASSWORD
